# Generated by Django 3.0.7 on 2020-08-18 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('main_img', models.ImageField(upload_to='images/')),
                ('hover_img', models.ImageField(upload_to='images/')),
                ('detail_img1', models.ImageField(upload_to='images/')),
                ('detail_img2', models.ImageField(upload_to='images/')),
                ('detail_img3', models.ImageField(upload_to='images/')),
                ('gender', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=5)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('couple', models.IntegerField()),
            ],
        ),
    ]
