# Generated by Django 3.0.7 on 2020-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200821_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
