# Generated by Django 3.0.7 on 2020-08-18 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200819_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=5),
        ),
    ]
