# Generated by Django 3.0.7 on 2020-08-18 16:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200819_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=5), size=1),
        ),
    ]
